
- hosts: PROD
  become_user: root
  tasks:
    - name: 1. instalando nodejs
      apt: name=node  state=latest

    - name: 2. instalando json-server
      npm:
        name: ['json-server']
        state: latest
    - name: 3. creando directorio
      mkdir /home/app
    - name: 4. configurando para el copiado 
      copy: src=Final.tar dest=/home/app/ mode=0664
    
    - name: 5. descomprimiendo archivo
      shell: tar -xvf Final.tar -C /home/app/
      
    - name: 6. cambiando permisos en el directorio  
      shell:  chmod -R 775 /home/app/
    - name: 7.  instalando dependencias
      shell  cd /home/app && npm install
      
